### ISSUE TITLE
Crash when using plugin

### ISSUE THREAD

**Issue by wxnnvs** [EaglerReborn/EaglerReborn#105] opened 2023-09-14 21:22 UTC
When i use the spider.js plugin from the original repo of eagler reborn i get this error:
_java.lang.RuntimeException: (JavaScript) TypeError: PluginAPI.player.reload is not a function
	at TypeError: PluginAPI.player.reload is not a function_

1. Open Eagler Reborn
2. Add official spider.js example plugin (https://raw.githubusercontent.com/EaglerReborn/EaglerReborn/main/exampleplugins/spider.js)
3. Walk into a wall

It should make me go up to wall like a spider

Windows 11
Opera GX

**Comment by wxnnvs** [comment] 2023-09-14 21:27
also, the jetpack plugin from radmanplays seems to work right: https://raw.githubusercontent.com/radmanplays/eaglerreborn-plugins/main/jetpack-v1.1.js

**Comment by wxnnvs** [comment] 2023-09-14 21:30
hm, i see, the PluginAPI.player.reload function is replaced by PluginAPI.updateComponent("player");

**Comment by OtterCodes102** [comment] 2023-09-14 21:32
Which version of Eagler Reborn are you using?

**Comment by wxnnvs** [comment] 2023-09-14 21:34
latest

**Comment by ZXMushroom63** [comment] 2023-09-15 00:09
add this to my todo list.

**Comment by ZXMushroom63** [comment] 2023-09-15 00:09
in the meanwhile, go back to the old updateComponent reload method.

**Comment by ZXMushroom63** [comment] 2023-09-15 00:15
btw can I see the error (the top part)
I'm imagining it says something like:
"Cannot read properties of undefined, reading 'reload' on 'player'"

**Comment by OtterCodes102** [comment] 2023-09-15 00:29
btw what do you think of the typescript plugin template i made?
https://github.com/EaglerReborn/reborn-example-plugin

**Comment by ZXMushroom63** [comment] 2023-09-15 00:33
I saw it, and it's really cool.
I'm probably going to use it for building my autofish plugin (after a6).

**Comment by ZXMushroom63** [comment] 2023-09-15 00:36
Right, just tried to reproduce the bug (yes, I made sure I was using the old plugin) and failed. The spider plugin works perfectly. Are you sure you're using the latest version?
(Open developer tools, type `PluginAPI.version` in the console, should say `a4.3`)

**Comment by ZXMushroom63** [comment] 2023-09-15 00:37
Also, I reckon I'll add a built-in client command for getting the version. (ie: .pluginapi)

**Comment by OtterCodes102** [comment] 2023-09-15 00:56
> Otherwise, it's kind of hard to code because you can't see what methods or properties are available.

might make a dummy API to fix this.

**Comment by ZXMushroom63** [comment] 2023-09-15 01:28
MIght be a bit of effort to maintain it, though.

**Comment by ZXMushroom63** [comment] 2023-09-15 03:51
@wxnnvs Are you sure you are using the latest compiled version of Eagler Reborn? Because I cannot reproduce the bug.

**Comment by wxnnvs** [comment] 2023-09-15 04:49
> Right, just tried to reproduce the bug (yes, I made sure I was using the old plugin) and failed. The spider plugin works perfectly. Are you sure you're using the latest version?
> (Open developer tools, type `PluginAPI.version` in the console, should say `a4.3`)

I'll try this today

**Comment by wxnnvs** [comment] 2023-09-15 06:02
My eagler reborn seems to be still on a3.1 i will try to get everything updated as soon as possible

**Comment by ZXMushroom63** [comment] 2023-09-17 23:58
Can I close this issue?

**Comment by wxnnvs** [comment] 2023-09-18 04:59
Yeah sure

**Closed** 2023-09-18 05:21 UTC
Labels: bug
